services:
  server:
    build: ./server
    ports:
      - 4000:4000

    command: npm run prod
    restart: always
    environment:
      - SERVER_PORT=4000
      - MODE_ENV=prod

  client:
    build: ./client
    command: npm run preview
    restart: always

    ports:
      - 4173:4173
